plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Naming/MethodParameterName:
  MinNameLength: 1

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
